# Generated by Django 5.0.3 on 2024-04-04 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_revenue', models.IntegerField(max_length=12)),
                ('cost_of_goods_sold', models.IntegerField(max_length=12)),
                ('dispatched_personnel_expenses', models.IntegerField(max_length=12)),
                ('personal_expenses', models.IntegerField(max_length=12)),
                ('expenses', models.IntegerField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='ClientMaster',
            fields=[
                ('client_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('registered_user_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyMaster',
            fields=[
                ('company_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('registered_user_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessDivisionMaster',
            fields=[
                ('business_division_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('business_division_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('registered_user_id', models.CharField(max_length=100)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.companymaster')),
            ],
        ),
        migrations.CreateModel(
            name='PlanningProjectData',
            fields=[
                ('planning_project_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('planning_project_name', models.CharField(max_length=100)),
                ('planning_project_type', models.CharField(max_length=50)),
                ('planning', models.DateField()),
                ('sales_revenue', models.IntegerField(max_length=12)),
                ('cost_of_goods_sold', models.IntegerField(max_length=12)),
                ('dispatched_personnel_expenses', models.IntegerField(max_length=12)),
                ('personal_expenses', models.IntegerField(max_length=12)),
                ('indirect_personal_expenses', models.IntegerField(max_length=12)),
                ('expenses', models.IntegerField(max_length=12)),
                ('operating_profit', models.IntegerField(max_length=12)),
                ('non_operating_income', models.IntegerField(max_length=12)),
                ('ordinary_profit', models.IntegerField(max_length=12)),
                ('ordinary_profit_margin', models.FloatField(max_length=10)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.clientmaster')),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceProjectData',
            fields=[
                ('project_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('sales_revenue', models.IntegerField(max_length=12)),
                ('cost_of_goods_sold', models.IntegerField(max_length=12)),
                ('dispatched_personnel_expenses', models.IntegerField(max_length=12)),
                ('personnel_expenses', models.IntegerField(max_length=12)),
                ('indirect_personnel_expenses', models.IntegerField(max_length=12)),
                ('expenses', models.IntegerField(max_length=12)),
                ('operating_profit', models.IntegerField(max_length=12)),
                ('non_operating_income', models.IntegerField(max_length=12)),
                ('ordinary_profit', models.IntegerField(max_length=12)),
                ('ordinary_profit_margin', models.FloatField(max_length=12)),
                ('planning_project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.planningprojectdata')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('registered_user_id', models.CharField(max_length=100)),
                ('affiliated_business_division_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.businessdivisionmaster')),
                ('affiliated_company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.companymaster')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
