version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    command: sh -c "gunicorn 'backend.wsgi' --bind=0.0.0.0:8000"
    restart: always
    volumes:
      - ./backend:/app
      - django_data:/var/lib/app_data
    ports:
      - "8000:8000"
    env_file:
      - .env

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client:/app
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend

volumes:
  data:
  django_data:
