export interface ExpenseResultEntity {
  expense_result_id: string | undefined
  year: string | undefined
  month: string | undefined
  consumable_expense: string | undefined
  rent_expense: string | undefined
  tax_and_public_charge: string | undefined
  depreciation_expense: string | undefined
  travel_expense: string | undefined
  communication_expense: string | undefined
  utilities_expense: string | undefined
  transaction_fee: string | undefined
  advertising_expense: string | undefined
  entertainment_expense: string | undefined
  professional_service_fee: string | undefined
  created_at: string | undefined
  updated_at: string | undefined
  expense_id: string | undefined
}
