name: Deployment

on:
  push:
    branches: ["main"]

jobs:
  client-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Run Build
        run: |
          cd ./client
          npm install
          if [ ! -d "./client/build" ]; then
            CI=false npm run build
          fi
      - name: Check if build directory is empty
        run: |
          if [ "$(ls -A ./client/build)" ]; then
            echo "Build directory is not empty"
          else
            echo "Build directory is empty. Exiting deployment."
            exit 1
          fi
      - name: copy file via ssh password
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.PUBLIC_DNS }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSH_PRIVATE_PEM_KEY }}
          source: "client/build/*"
          target: "/usr/share/nginx/html/"
      - name: Sync frontend build files
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.PUBLIC_DNS }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSH_PRIVATE_PEM_KEY }}
          script: rsync -av --delete client/build/ /usr/share/nginx/html/
      - name: Restart Nginx service
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.PUBLIC_DNS }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSH_PRIVATE_PEM_KEY }}
          script: |
            rsync -av --delete /usr/share/nginx/html/client/build/ /usr/share/nginx/html/
            rm -rf /usr/share/nginx/html/client/
