name: Deployment

on:
  push:
    branches: ["main"]

jobs:
  client-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Run Build
        run: |
          npm install
          if [ ! -d "./build" ]; then
              CI=false npm run build
          fi
        working-directory: ./

      - name: Copy build files via SSH
        uses: appleboy/scp-action@master
        with:
          host: ec2-54-178-202-58.ap-northeast-1.compute.amazonaws.com
          username: ec2-user
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "build/*"
          target: "/home/ec2-user/build"
          strip_components: 2

      - name: Check EC2 Instance Directory
        run: |
          ssh -i ${{ secrets.SSH_PRIVATE_KEY }} ec2-user@ec2-54-178-202-58.ap-northeast-1.compute.amazonaws.com ls -al /home/ec2-user/build
